package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.w3c.dom.Text;

import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Condition.visible;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;
import static com.codeborne.selenide.Selectors.byText;


public class GeneratedTests extends TestBase {

    @Test
    @Description("Test Autorization")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Открыть url 'https://www.litres.ru/'", () ->
                open("https://www.litres.ru/"));

        step("выбор иконки лк", () ->
                $(".Login-module__loginLink").click());

        step("выбор ", () -> $(".Button-module__primary_orange").click());

        step("ввод логина", () -> $(".AuthorizationPopup-module__input").setValue("delkabo@yandex.ru"));

        step("клик по кнопке", () -> $(".childContainer-0-2-4").click());

        step("ввод пароля", () -> $(".AuthorizationPopup-module__input").setValue("Kam1naLitRes969!"));

        step("подтверждение ввода пароля", () -> $(".childContainer-0-2-4").click());

        step("проверка присутствия иконки аватарки", () ->
                $(".Profile-module__profileLink").shouldHave(visible));
    }

        @Test
        @Description("Find Book")
        @DisplayName("find book 'Война и Мир'")
        void findBook() {

            step("Открыть url 'https://www.litres.ru/'", () ->
                    open("https://www.litres.ru/"));

            step("ввод книги 'Война и Мир' в строку поиска", () ->
                    $(".Search-module__input").setValue("Война и мир").pressEnter());

            step("проверка нахождения книги 'Война и Мир' в списке", () ->
                    $("#search__content").shouldHave(text("Война и мир")));
        }

    @Test
    @Description("Найти раздел Подработки")
    @DisplayName("Найти раздел Подработки")
    void test1() {

        step("Открыть url 'https://www.litres.ru/'", () ->
                open("https://www.litres.ru/"));

        step("Кликнуть по кнопке 'Жанры'", () ->
                $(".LowerMenu-module__popoverContentWrapp").click());

        step("Выбрать из списка 'Подборки'", () ->
                $$(".MoreMenu-module__text").findBy(text("Подборки")).click());

        step("Найти Название 'Подборки' на странице", () ->
                $(".grouped__collection").shouldHave(text("Подборки")));
    }

    @Test
    @Description("Find Book")
    @DisplayName("find book 'Война и Мир'")
    void checkPopular() {

        step("Открыть url 'https://www.litres.ru/'", () ->
                open("https://www.litres.ru/"));

        step("Выбрать раздел популярное из списка", () ->
                $$(".LowerMenu-module__item").findBy(text("Популярное")).click());

        step("choose enter in lk", () ->
                $(".book_ratings").shouldHave(text("Книжные бестселлеры")));
    }

    @Test
    @Description("check 'хобби и досуг'")
    @DisplayName("check 'хобби и досуг'")
    void test3() {

        step("Открыть url 'https://www.litres.ru/'", () ->
                open("https://www.litres.ru/"));

        step("Кликнуть по кнопке жанры", () ->
                $(".LowerMenu-module__genres").click());

        step("Найти в списке 'Хобби, досуг'", () ->
        $("div[data-header-popup=\"genres\"]").$(byText("Хобби, досуг")).click());

        step("Проверить название 'Хобби, досуг' на странице", () ->
                $(".new-container").shouldHave(text("Хобби, досуг")));
    }

// удалить тест ниже
    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://github.com/login'", () ->
            open("https://github.com/login"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}